### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by geekscruff** [ULCC/dog_biscuits#7]
work generator should

-- check if the hyrax generator has been run already
-- run the hyrax generator

-- insert into form
-- insert into presenter
-- insert into model

-- add attribute rows

**Comment by geekscruff** [comment]
- [ ] check locales generation
- [ ] catalog controller adds *all* properties, but some of models might not be selected
- [ ] in ^^ case, might need a 'selected models' config

**Comment by geekscruff** [comment]
```
 blacklight:
    search:
      fields:
        facet:
        index:
        show:
```
